Reset permissions if directory can't be deleted.
git-svn-id: svn+ssh://svn.debian.org/svn/pkg-utopia/packages/unstable/avahi@3376 ceb527fc-18e6-0310-9fe2-813c157c29e7

diff --git a/debian/avahi-daemon.postrm b/debian/avahi-daemon.postrm
--- a/debian/avahi-daemon.postrm
+++ b/debian/avahi-daemon.postrm
@@ -7,6 +7,8 @@ set -e
 if [ "$1" = "purge" ] ; then
         deluser --quiet --system avahi > /dev/null || true
         delgroup --quiet --system avahi > /dev/null || true
-        rmdir --ignore-fail-on-non-empty /var/run/avahi-daemon
+        # Cleanup /var/run/avahi-daemon, see #448539
+        f=/var/run/avahi-daemon
+        rmdir "$f" || { chown root:root "$f" && chmod 00700 "$f"; }
 fi
 
