* debian/avahi-autoipd.postrm   - Cleanup /var/run/avahi-daemon on "purge". (Closes: #527925)
git-svn-id: svn+ssh://svn.debian.org/svn/pkg-utopia/packages/unstable/avahi@3377 ceb527fc-18e6-0310-9fe2-813c157c29e7

diff --git a/debian/avahi-daemon.postrm b/debian/avahi-daemon.postrm
--- a/debian/avahi-daemon.postrm
+++ b/debian/avahi-daemon.postrm
@@ -5,10 +5,12 @@ set -e
 #DEBHELPER#
 
 if [ "$1" = "purge" ] ; then
-        deluser --quiet --system avahi > /dev/null || true
-        delgroup --quiet --system avahi > /dev/null || true
-        # Cleanup /var/run/avahi-daemon, see #448539
-        f=/var/run/avahi-daemon
+    deluser --quiet --system avahi > /dev/null || true
+    delgroup --quiet --system avahi > /dev/null || true
+    # Cleanup /var/run/avahi-daemon, see #448539
+    f=/var/run/avahi-daemon
+    if [ -d "$f" ]; then
         rmdir "$f" || { chown root:root "$f" && chmod 00700 "$f"; }
+    fi
 fi
 
